%% Load and resave analysed data
found_wave_idx = x_found;
found_network = y_found;

folder = 'L:\BN\HY\Shared\Yiteng\two_signals\trav_wave_stability_general';
fname_str = 'trav_wave_conditions_check_wave_num_1_type_1_analysed_run3_vary_a0_lambda12_with_Qvals';
fname = fullfile(folder, fname_str);
save(fname, 'N', 'P', 'rcell', 'a0', 'lambda',...
'bandwidth',...
'num_waves',...
'wave_type',...
'networks_idx',...
'n_pset',...
'subfolder',...
'wave_types_str',...
'wave_possible',...
'found_wave_idx',...
'found_network',...
'Qvals');
%%
