%time_evolution_two_signals_save_network33;
time_evolution_two_signals_save_network34;
time_evolution_two_signals_save_network36;
time_evolution_two_signals_save_network15;
time_evolution_two_signals_save_network19;
